laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home')->middleware('guest.aluno');

    Route::group(['middleware' => 'auth.aluno'], function() {
        Route::get('vagas', 'VagasController@index')->name('vagas');
        Route::get('vagas/{vagas}/{tipo}', 'VagasController@show')->name('vagas.info');
    });

    Route::group(['namespace' => 'Auth'], function() {
        Route::post('login', 'AuthAlunoController@login')->name('aluno.login');
        Route::get('logout', 'AuthAlunoController@logout')->name('aluno.logout');
    });

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('vagas/cursos', 'VagasCursosController', ['parameters' => ['cursos' => 'cursos_vagas']]);
        Route::resource('vagas', 'VagasController');

        Route::get('relatorios/vagas', 'RelatoriosController@vagas')->name('painel.relatorios.vagas');
        Route::get('relatorios/cliques', 'RelatoriosController@cliques')->name('painel.relatorios.cliques');
        Route::get('relatorios/termos', 'RelatoriosController@termos')->name('painel.relatorios.termos');
        Route::get('relatorios/cursos', 'RelatoriosController@cursos')->name('painel.relatorios.cursos');
        Route::get('relatorios/vagas-preenchidas', 'RelatoriosController@preenchidas')->name('painel.relatorios.preenchidas');

		Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);

        // Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        // Route::resource('contato/recebidos', 'ContatosRecebidosController');
        // Route::resource('contato', 'ContatoController');

        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/RelatoriosController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Helpers\Tools;
use Illuminate\Http\Request;

use App\Http\Controllers\Controller;

use App\Models\Vaga;
use App\Models\VagaCurso;
use App\Models\VagaVisualizacao;
use App\Models\TermoBuscado;
use App\Models\CursoBuscado;

use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class RelatoriosController extends Controller
{
    public function vagas(Request $request)
    {
        $cursos = VagaCurso::ordenados()->lists('titulo', 'id');
        $vagas  = new Vaga;

        if ($curso = $request->get('curso')) {
            $vagas = $vagas->whereHas('cursos', function($query) use ($curso) {
                $query->where('vaga_curso.vaga_curso_id', (int) $curso);
            });
        }

        $total  = $vagas->count();
        $ativas = $vagas->emExibicao()->count();

        return view('painel.relatorios.vagas', compact('cursos', 'total', 'ativas'));
    }

    public function cliques(Request $request)
    {
        $cursos  = VagaCurso::ordenados()->lists('titulo', 'id');
        $cliques = $this->filtraPeriodo($request, new VagaVisualizacao);

        if ($termo = $request->get('termo')) {
            $cliques = $cliques->whereHas('vaga', function($query) use ($termo) {
                $query->where('titulo', 'LIKE', "%$termo%");
            });
        }

        if ($curso = $request->get('curso')) {
            $cliques = $cliques->whereHas('vaga.cursos', function($query) use ($curso) {
                $query->where('vaga_curso.vaga_curso_id', (int) $curso);
            });
        }

        $cliques = $cliques
            ->with('vaga')
            ->groupBy('vaga_id')
            ->select('vaga_id', DB::raw('count(*) as total'))
            ->orderBy('total', 'DESC')
            ->paginate(20);

        return view('painel.relatorios.cliques', compact('cursos', 'cliques'));
    }

    public function termos(Request $request)
    {
        $termos = $this->filtraPeriodo($request, new TermoBuscado);
        $termos = $termos
            ->groupBy('termo')
            ->select('termo', DB::raw('count(*) as total'))
            ->orderBy('total', 'DESC')
            ->orderBy('termo', 'ASC')
            ->paginate(20);

        return view('painel.relatorios.termos', compact('termos'));
    }

    public function cursos(Request $request)
    {
        $cursos = $this->filtraPeriodo($request, new CursoBuscado);
        $cursos = $cursos
            ->with('curso')
            ->groupBy('curso_id')
            ->select('curso_id', DB::raw('count(*) as total'))
            ->orderBy('total', 'DESC')
            ->get();

        return view('painel.relatorios.cursos', compact('cursos'));
    }

    public function preenchidas(Request $request)
    {
        if ($filter = $request->get('por')) {
            if (!in_array($filter, array_keys(Tools::vagaStatus()))) {
                abort('404');
            }

            $vagas = Vaga::where('preenchida', $filter)
                ->orderBy('data_de_cadastro', 'DESC')
                ->paginate(20);

            return view('painel.relatorios.preenchidas.list', compact('vagas'));
        }

        $contagem = Vaga::whereNotNull('preenchida')
            ->groupBy('preenchida')
            ->select('preenchida', DB::raw('count(*) as total'))
            ->lists('total', 'preenchida');

        return view('painel.relatorios.preenchidas.contagem', compact('contagem'));
    }

    protected function filtraPeriodo(Request $request, $registros)
    {
        $inicio = null;
        $final  = null;

        try {
            if ($request->get('data_inicio') && Carbon::createFromFormat('d/m/Y', $request->get('data_inicio'))) {
                $inicio = Carbon::createFromFormat('d/m/Y', $request->get('data_inicio'))->format('Y-m-d');
            }
            if ($request->get('data_final') && Carbon::createFromFormat('d/m/Y', $request->get('data_final'))) {
                $final = Carbon::createFromFormat('d/m/Y', $request->get('data_final'))->format('Y-m-d');
            }
        } catch (\Exception $e) {
        }

        if ($inicio) {
            $registros = $registros->whereDate('created_at', '>=', $inicio);
        }
        if ($final) {
            $registros = $registros->whereDate('created_at', '<=', $final);
        }

        return $registros;
    }
}

laravel/resources/views/painel/relatorios/preenchidas/contagem.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Relatórios /</small> Vagas Preenchidas</h2>
    </legend>

    <div class="row" style="margin-top:30px">
        @foreach(Tools::vagaStatus() as $key => $label)
        <div class="col-md-4">
            <a href="{{ route('painel.relatorios.preenchidas', ['por' => $key]) }}" class="panel panel-default">
                <div class="panel-heading">{{ $label }}</div>
                <div class="panel-body">
                    <h1 style="margin:0;display:inline">{{ $contagem->has($key) ? $contagem[$key] : 0 }}</h1>
                    <h4 style="display:inline-block;margin-left:5px">vagas</h4>
                </div>
            </a>
        </div>
        @endforeach
    </div>

    <style>
        .panel { display: block; color: inherit; }
        .panel:hover { text-decoration: none; }
    </style>

@endsection

laravel/resources/views/painel/relatorios/preenchidas/list.blade.php
@extends('painel.common.template')

@section('content')

    <a href="{{ route('painel.relatorios.preenchidas') }}" class="btn btn-sm btn-default">
        &larr; Voltar
    </a>

    <legend>
        <h2><small>Relatórios / Vagas preenchidas /</small> {{ Tools::vagaStatus()[request('por')] }}</h2>
    </legend>

    <div class="row">
        <div class="col-lg-8">
            @if(!count($vagas))
            <div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
            @else
            <table class="table table-striped table-bordered table-hover table-info">
                <thead>
                    <tr>
                        <th>Vaga</th>
                        <th>Preenchida em</th>
                        <th>Preenchida por</th>
                    </tr>
                </thead>

                <tbody>
                @foreach ($vagas as $vaga)
                    <tr class="tr-row">
                        <td>
                            <a href="{{ route('painel.vagas.edit', $vaga->id) }}">
                                {{ $vaga->titulo }}
                            </a>
                        </td>
                        <td>{{ $vaga->preenchida_em->format('d/m/Y H:i') }}</td>
                        <td>
                            <a href="{{ route('painel.usuarios.edit', $vaga->preenchidaPor->id) }}">
                                {{ $vaga->preenchidaPor->name }}
                            </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

            {!! $vagas->appends($_GET)->render() !!}
            @endif
        </div>
    </div>

@endsection