laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home')->middleware('guest.aluno');

    Route::group(['middleware' => 'auth.aluno'], function() {
        Route::get('vagas', 'VagasController@index')->name('vagas');
        Route::get('vagas/{vagas}/{tipo}', 'VagasController@show')->name('vagas.info');
    });

    Route::group(['namespace' => 'Auth'], function() {
        Route::post('login', 'AuthAlunoController@login')->name('aluno.login');
        Route::get('logout', 'AuthAlunoController@logout')->name('aluno.logout');
    });

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('vagas/cursos', 'VagasCursosController', ['parameters' => ['cursos' => 'cursos_vagas']]);
        Route::resource('vagas', 'VagasController');

        Route::get('relatorios/vagas', 'RelatoriosController@vagas')->name('painel.relatorios.vagas');
        Route::get('relatorios/cliques', 'RelatoriosController@cliques')->name('painel.relatorios.cliques');
        Route::get('relatorios/termos', 'RelatoriosController@termos')->name('painel.relatorios.termos');
        Route::get('relatorios/cursos', 'RelatoriosController@cursos')->name('painel.relatorios.cursos');
        Route::get('relatorios/vagas-preenchidas', 'RelatoriosController@preenchidas')->name('painel.relatorios.preenchidas');

		Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);

        // Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        // Route::resource('contato/recebidos', 'ContatosRecebidosController');
        // Route::resource('contato', 'ContatoController');

        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Models/Vaga.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

use Carbon\Carbon;

class Vaga extends Model
{
    protected $table = 'vagas';

    protected $guarded = ['id'];

    protected $dates = [
        'data_de_cadastro',
        'data_de_expiracao',
        'cadastrada_em',
        'preenchida_em'
    ];

    public function cursos()
    {
        return $this->belongsToMany('App\Models\VagaCurso', 'vaga_curso', 'vaga_id', 'vaga_curso_id')->ordenados();
    }

    public function setDataDeCadastroAttribute($date)
    {
        if ($date) {
            $this->attributes['data_de_cadastro'] = Carbon::createFromFormat('d/m/Y', $date)->format('Y-m-d');
        } else {
            $this->attributes['data_de_cadastro'] = null;
        }
    }

    public function getDataCadastroAttribute()
    {
        return $this->data_de_cadastro->format('d/m/Y');
    }

    public function setDataDeExpiracaoAttribute($date)
    {
        if ($date) {
            $this->attributes['data_de_expiracao'] = Carbon::createFromFormat('d/m/Y', $date)->format('Y-m-d');
        } else {
            $this->attributes['data_de_expiracao'] = null;
        }
    }

    public function getDataFormatadaAttribute()
    {
        return $this->data_de_expiracao
            ? $this->data_de_expiracao->format('d/m/Y')
            : null;
    }

    public static function niveis()
    {
        return [
            'tecnico'   => 'Nível Técnico',
            'graduacao' => 'Graduação',
        ];
    }

    public function getEmExibicaoAttribute()
    {
        if ($this->data_de_expiracao && Carbon::now()->gt($this->data_de_expiracao)) {
            return false;
        }

        return $this->ativa && !$this->preenchida;
    }

    public function scopeEmExibicao($query)
    {
        return $query
            ->where('ativa', 1)
            ->where(function($query) {
                $query
                    ->whereNull('data_de_expiracao')
                    ->orWhereDate('data_de_expiracao', '>', Carbon::now());
            });
    }

    public function cadastradaPor()
    {
        return $this->belongsTo(User::class, 'cadastrada_por');
    }

    public function preenchidaPor()
    {
        return $this->belongsTo(User::class, 'preenchida_por');
    }
}

laravel/app/Http/Controllers/Painel/VagasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\VagasRequest;
use App\Http\Controllers\Controller;

use App\Models\Vaga;
use App\Models\VagaCurso;
use Carbon\Carbon;

class VagasController extends Controller
{
    private $cursos;

    public function __construct()
    {
        $this->cursos = VagaCurso::ordenados()->lists('titulo', 'id');
    }

    public function index()
    {
        $registros = Vaga::orderBy('data_de_cadastro', 'DESC')->paginate(20);

        return view('painel.vagas.index', compact('registros'));
    }

    public function create()
    {
        $cursos = $this->cursos;

        return view('painel.vagas.create', compact('cursos'));
    }

    public function store(VagasRequest $request)
    {
        try {

            $input = $request->except('cursos');
            $cursos  = ($request->get('cursos') ?: []);

            $input['nivel'] = implode(',', $request->get('nivel'));

            if (!$input['data_de_expiracao']) {
                $input['data_de_expiracao'] = null;
            }

            $input['cadastrada_em'] = Carbon::now();
            $input['cadastrada_por'] = auth()->user()->id;

            $registro = Vaga::create($input);
            $registro->cursos()->sync($cursos);

            return redirect()->route('painel.vagas.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Vaga $registro)
    {
        $cursos = $this->cursos;

        return view('painel.vagas.edit', compact('registro', 'cursos'));
    }

    public function update(VagasRequest $request, Vaga $registro)
    {
        try {

            $input = $request->except('cursos');

            $input['nivel'] = implode(',', $request->get('nivel'));

            if (!$input['data_de_expiracao']) {
                $input['data_de_expiracao'] = null;
            }

            if (!$input['preenchida']) {
                $input['preenchida'] = null;
                $input['preenchida_em'] = null;
                $input['preenchida_por'] = null;
            } else if ($input['preenchida'] !== $registro->preenchida) {
                $input['preenchida_em'] = Carbon::now();
                $input['preenchida_por'] = auth()->user()->id;
            }

            $registro->update($input);

            $cursos = ($request->get('cursos') ?: []);
            $registro->cursos()->sync($cursos);

            return redirect()->route('painel.vagas.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Vaga $registro)
    {
        try {

            $registro->cursos()->detach();
            $registro->delete();

            return redirect()->route('painel.vagas.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/VagasController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\Tools;
use Illuminate\Http\Request;

use App\Models\Vaga;
use App\Models\VagaCurso;
use App\Models\VagaVisualizacao;
use App\Models\CursoBuscado;
use App\Models\TermoBuscado;

class VagasController extends Controller
{
    public function index(Request $request)
    {
        if ($request->has('page') && !$request->ajax()) {
            return redirect()->route('vagas', $request->except('page'));
        }

        $aluno  = auth('aluno')->user();
        $niveis = Vaga::niveis();
        $cursos = VagaCurso::ordenados()->get();

        $vagas = Vaga::with('cursos')->emExibicao()->orderBy('data_de_cadastro', 'DESC');

        $vagas = $vagas->where(function($query) use ($request) {
            foreach(Vaga::niveis() as $slug => $nivel) {
                if ($request->get($slug)) {
                    $query->orWhere('nivel', 'LIKE', "%$nivel%");
                }
            }
        });

        if ($curso = $request->get('curso')) {
            $vagas = $vagas->whereHas('cursos', function($query) use ($curso) {
                $query->where('slug', $curso);
            });


            $cursoObj = $cursos->where('slug', $curso)->first();
            if (!request()->has('page') && $cursoObj) {
                CursoBuscado::create([
                    'curso_id'      => $cursoObj->id,
                    'usuario_id'    => $aluno->id,
                    'usuario_email' => $aluno->email
                ]);
            }
        }

        if ($termo = $request->get('termo')) {
            $vagas = $vagas
                ->where('titulo', 'LIKE', "%$termo%")
                ->orWhere('descricao', 'LIKE', "%$termo%");

            if (!request()->has('page')) {
                TermoBuscado::create([
                    'termo'         => $termo,
                    'usuario_id'    => $aluno->id,
                    'usuario_email' => $aluno->email
                ]);
            }
        }

        $vagas = $vagas->paginate(6);

        if ($request->ajax()) {
            return response()->json([
                'body' => view('frontend._vagas', compact('vagas'))->render(),
                'end'  => !$vagas->hasMorePages()
            ]);
        }

        return view('frontend.vagas', compact('niveis', 'cursos', 'vagas'));
    }

    public function show(Vaga $vaga, $tipo) {
        $aluno = auth('aluno')->user();

        $text = null;
        $link = null;

        if ($tipo == 'telefone' && $vaga->telefone) {
            $text = $vaga->telefone;
        } else if ($tipo == 'e_mail' && $vaga->e_mail) {
            $text = $vaga->e_mail;
            $link = 'mailto:'.$vaga->e_mail;
        } else if ($tipo == 'site' && $vaga->site) {
            $text = $vaga->site;
            $link = Tools::parseLink($vaga->site);
        }

        VagaVisualizacao::firstOrCreate([
            'vaga_id'       => $vaga->id,
            'usuario_id'    => $aluno->id,
            'usuario_email' => $aluno->email
        ]);

        return response()->json(compact('text', 'link'));
    }
}

laravel/resources/views/painel/vagas/cursos/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Vagas /</small> Adicionar Curso</h2>
    </legend>

    {!! Form::open(['route' => 'painel.vagas.cursos.store']) !!}

        @include('painel.vagas.cursos.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/vagas/cursos/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Vagas /</small> Editar Curso</h2>
    </legend>

    {!! Form::model($curso, [
        'route'  => ['painel.vagas.cursos.update', $curso->id],
        'method' => 'patch'])
    !!}

    @include('painel.vagas.cursos.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/vagas/cursos/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('titulo', 'Título') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.vagas.cursos.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/vagas/cursos/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <a href="{{ route('painel.vagas.index') }}" title="Voltar para Vagas" class="btn btn-sm btn-default">
        &larr; Voltar para Vagas    </a>

    <legend>
        <h2>
            <small>Vagas /</small> Cursos

            <a href="{{ route('painel.vagas.cursos.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Curso</a>
        </h2>
    </legend>

    @if(!count($cursos))
    <div class="alert alert-warning" role="alert">Nenhum curso cadastrado.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-sortable" data-table="vagas_cursos">
        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Título</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($cursos as $curso)
            <tr class="tr-row" id="{{ $curso->id }}">
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                <td>{{ $curso->titulo }}</td>
                <td class="crud-actions">
                    {!! Form::open(array('route' => array('painel.vagas.cursos.destroy', $curso->id), 'method' => 'delete')) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.vagas.cursos.edit', $curso->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @endif

@endsection